### my-profile
GET http://localhost:3000/my-profile HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODQyYThlYy1mYmRmLTRhMGQtYmZkMS04NGFkMTM5NjllNjciLCJyb2xlIjoiR1VBUkRFRCIsImlhdCI6MTUxNjIzOTAyMn0.cw9zw70Y6xi41RDYN3zknJLncMwT7H9hOIT0Az1ZPRA

### my-registers
GET http://localhost:3000/my-registers?type=IN&start=2023-11-21T02:00:45.387Z&end=2023-11-21T02:00:45.387Z HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODQyYThlYy1mYmRmLTRhMGQtYmZkMS04NGFkMTM5NjllNjciLCJyb2xlIjoiR1VBUkRFRCIsImlhdCI6MTUxNjIzOTAyMn0.cw9zw70Y6xi41RDYN3zknJLncMwT7H9hOIT0Az1ZPRA

### my-code
GET http://localhost:3000/my-code HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTE5NGNhNS0wNDI1LTRiYWYtOWE4Yi03OWJmM2UzZmRlMmMiLCJyb2xlIjoiR1VBUkRFRCIsImlhdCI6MTcwMDcwNzM1NywiZXhwIjoxNzAwNzA3NDE3fQ.tq04btRfh7EcfiDkznvb9THQNpjIKNP8FqDRBIQodh0

### refresh-code
PATCH http://localhost:3000/refresh-my-code HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODQyYThlYy1mYmRmLTRhMGQtYmZkMS04NGFkMTM5NjllNjciLCJyb2xlIjoiR1VBUkRFRCIsImlhdCI6MTUxNjIzOTAyMn0.cw9zw70Y6xi41RDYN3zknJLncMwT7H9hOIT0Az1ZPRA

### my-guardeds
GET http://localhost:3000/my-guardeds HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

### my-guarded-registers
GET http://localhost:3000/my-guarded-registers?guarded=c842a8ec-fbdf-4a0d-bfd1-84ad13969e67 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OGRkNWFjMi03YWE2LTQ1YTQtYjNlZC0yZmI1NjAyOWUyMTYiLCJyb2xlIjoiR1VBUkRJQU4iLCJpYXQiOjE1MTYyMzkwMjJ9.xhKWlya19xRD7awBdzqQJ-b6l6WzsMrTOIGi50btw-Y

### create-register
POST http://localhost:3000/create-register HTTP/1.1
Content-Type: application/json

{
    "fingerprint": "ee27bc41-fd3e-4a0b-84cb-48fb51f2c421"
}