###
POST http://localhost:3000/auth HTTP/1.1
Content-Type: application/json

{
    "email": "ademir@gmail.com",
    "password": "ademir123"
}

###
POST http://localhost:3000/auth HTTP/1.1
Content-Type: application/json

{
    "email": "johndoe@mail.com",
    "password": "123456"
}

###
POST http://localhost:3000/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
    "refresh_token": "bbd5745d-859e-470f-8003-fde6ee6712e2"
}