### 1. Create a guard relation
POST http://localhost:3000/guard-relation HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
Content-Type: application/json

{
  "guarded_id": "<uuid>",
  "guardian_id": "<uuid>"
}

### 2. Get all guards relationship

// Page query param

// page: optional (recive 0 by default)
// take: optional (recive 8 by default)

// Filter query param

// * if the optional query param is not provided, don't filter by that field *
// guarded: optional (find for registers that the user id are equals to the guarded id provided)
// guardian: optional (find for registers that the role id are equals to the guardian id provided)

GET http://localhost:3000/guard-relation HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

### 3. Delete a guard relation

// * To delete a guard relation, you need to provide the guarded id and the guardian id by query params *

DELETE http://localhost:3000/guard-relation?guarded=<uuid>&&guardian=<uuid> HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo