### 1. Create a user

// JSON body

// active: optional (recive true by default)
// name: required
// email: required
// password: optional (recive a uuid by default)
// fingerprint: optional (recive a uuid by default)
// enrollment: optional (nullable)
// birth: optional (nullable)
// shift: optional (nullable)
// guardeds: optional (nullable) (you need to provide an array of id of the guardeds, like the example below)

//  "guardeds": [
//    {
//      "id": <uuid>
//    }
//  ]

//  "roles": [
//    {
//      "id": <uuid>
//    }
//  ]


POST http://localhost:3000/user HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
Content-Type: application/json

{
  "name": "Vinicius Diefenbach",
  "email": "viniciusdiefenbach@gmail.com",
  "password": "vinidiefen",
  "fingerprint": "vinicius diefenbach fingerprint",
  "enrollment": "20231sg.inf_i0098",
  "birth": "2004-05-12",
  "shift": "MORNING",
  "roles": [
    {
      "id": "ba4b0676-142b-481b-b15c-9af7da2e3004"
    },
    {
      "id": "15302eb1-ee3e-4e77-8934-e53a238d1e41"
    }
  ]
}

###
POST http://localhost:3000/user HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@mail.com",
  "password": "123456",
  "fingerprint": "john doe fingerprint",
  "roles": [
    {
      "id": "97ff860c-b811-4b44-b3a6-7ae85921a36a"
    }
  ],
  "guardeds": [
    {
      "id": "<uuid vini>"
    }
  ]
}

###
POST http://localhost:3000/user HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
Content-Type: application/json

{
  "name": "Kauê Soares",
  "email": "kauesoares@gmail.com",
  "password": "kauesoares",
  "fingerprint": "kaue soares fingerprint",
  "enrollment": "20231sg.inf_i0007",
  "birth": "2003-12-17",
  "shift": "AFTERNOON",
  "roles": [
    {
      "id": "15302eb1-ee3e-4e77-8934-e53a238d1e41"
    }
  ]
}

###
POST http://localhost:3000/user HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
Content-Type: application/json

{
  "name": "Maria Soares",
  "email": "mariasoares@gmail.com",
  "password": "mariasoares",
  "fingerprint": "maria soares fingerprint",
  "enrollment": "20251sg.inf_i0015",
  "birth": "2010-02-06",
  "shift": "MORNING",
  "roles": [
    {
      "id": "15302eb1-ee3e-4e77-8934-e53a238d1e41"
    }
  ]
}

###
POST http://localhost:3000/user HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
Content-Type: application/json

{
  "name": "Molly Allyson",
  "email": "molyallyson@mail.com",
  "password": "123456",
  "fingerprint": "molly allyson fingerprint",
  "roles": [
    {
      "id": "97ff860c-b811-4b44-b3a6-7ae85921a36a"
    }
  ],
  "guardeds": [
    {
      "id": "<uuid kaue>"
    }
  ]
}

### 2. Get all the users

// Page query param

// page: optional (recive 0 by default)
// limit: optional (recive 8 by default)

// Filter query param

// * if the optional query param is not provided, don't filter by that field *
// active: optional (find for registers that are active or not) (you need to provide true or false - a boolean value)
// name: optional (find for registers that contains the name)
// email: optional (find for registers that contains the email)
// shift: optional (find for registers that the shift are equals to the shift provided)

GET http://localhost:3000/user HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

###
GET http://localhost:3000/user?active=false HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

###
GET http://localhost:3000/user?limit=1 HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

###
GET http://localhost:3000/user?limit=1&page=1 HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

###
GET http://localhost:3000/user?name=John D HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

###
GET http://localhost:3000/user?email=johndoe@mail.co HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

###
GET http://localhost:3000/user?shift=MORNING HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

### 3. Get a user by id
GET http://localhost:3000/user/<uuid> HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

### 4. Update a user
PATCH http://localhost:3000/user/<uuid> HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
Content-Type: application/json

{
  "active": true
}

### 5. Delete a user
DELETE http://localhost:3000/user/<uuid> HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
