### 1. Create a user role relation
POST http://localhost:3000/user-role-relation HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo
Content-Type: application/json

{
  "user_id": "<uuid>",
  "role_id": "<uuid>"
}

### 2. Get all user roles relationship

// Page query param

// page: optional (recive 0 by default)
// take: optional (recive 8 by default)

// Filter query param

// * if the optional query param is not provided, don't filter by that field *
// user: optional (find for registers that the user id are equals to the user id provided)
// role: optional (find for registers that the role id are equals to the role id provided)

GET http://localhost:3000/user-role-relation HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo

### 3. Delete a user role relation

// * To delete a user role relation, you need to provide the user id and the role id by query params *

DELETE http://localhost:3000/user-role-relation?role=<uuid>&&user=<uuid> HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyY2QxYmMyOC03OTgxLTQwNjktYmRiNC1mN2NhZTNmZmU3MTMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.nUhCjjIkx-osh65eF4YLzNiFqqReEFP0MnbCt6RFEEo